<?php

/**
 * @file
 * Provides fomatter integration of the HERE Maps JS API with the Geofield.
 */

/**
 * Implements hook_menu().
 */
function here_maps_formatter_menu() {
  $items = array();

  $items['admin/config/here_maps'] = array(
    'title' => 'HERE Maps Keys',
    'description' => 'Configuration page for HERE Maps keys.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('here_maps_formatter_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * FAPI for map's API keys settings page.
 */
function here_maps_formatter_admin_settings($form, &$form_state) {
  $form = array();

  $form['here_maps'] = array(
    '#title' => t('HERE Maps Keys'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['here_maps']['here_maps_formatter_app_id'] = array(
    '#title' => t('HERE Maps App ID'),
    '#type' => 'textfield',
    '#default_value' => variable_get('here_maps_formatter_app_id', 'DemoAppId01082013GAL'),
  );

  $form['here_maps']['here_maps_formatter_app_code'] = array(
    '#title' => t('HERE Maps App Code'),
    '#type' => 'textfield',
    '#default_value' => variable_get('here_maps_formatter_app_code', 'AJKnXv84fjrb0KIHawS0Tg'),
  );

  // Create a system-generated submit form. This is equivalent to:
  // $form['#submit'][] = 'system_settings_form_submit';
  // The advantage of this 'submit' callback is the automatic calling
  // of the corresponding variable_set() for the form elements of the same name:
  // 'here_maps_app_id' and 'here_maps_app_code'.
  $form = system_settings_form($form);

  return $form;
}


/**
 * Implements hook_field_formatter_info().
 */
function here_maps_formatter_field_formatter_info() {
  $formatters = array();

  if (module_exists('geofield')) {
    // Set the machine name, label, and field type to be associated with.
    // It means also that Geofield is a dependency.
    $formatters['geofield_here_maps'] = array(
      'label' => t('HERE Maps'),
      'field types' => array('geofield'),
      'settings'  => array(
        // Give default values when the form is first loaded.
        'width' => 600,
        'width_unit' => 'px',
        'height' => 400,
        'zoom' => 12,
        'base_map' => 'Normal',
        'connection_protocol' => 'http',
        'map_settings' => 1,
        'zoom_bar' => 1,
        'scale_bar' => 1,
        'marker_color' => '#1188dd',
      ),
    );
  }

  return $formatters;
}


/**
 * Implements hook_field_formatter_settings_form().
 */
function here_maps_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  // Get the view_mode where our settings are stored.
  $display = $instance['display'][$view_mode];

  // Get the actual settings.
  $settings = $display['settings'];

  // Initialize the element variable.
  $element = array();

  if ($display['type'] == 'geofield_here_maps') {
    $element['width'] = array(
      '#title' => t('Map Width'),
      '#type' => 'textfield',
      '#size' => 5,
      '#required' => TRUE,
      '#default_value' => $settings['width'],
      '#element_validate' => array('element_validate_integer_positive'),
      '#prefix' => '<div><div style="float: left">',
      '#suffix' => '</div>',
    );

    $element['width_unit'] = array(
      '#type' => 'select',
      '#default_value' => $settings['width_unit'],
      '#options' => array(
        'px' => t('px'),
        'em' => t('em'),
        '%' => t('%'),
      ),
      '#prefix' => '<div>',
      '#suffix' => '</div></div>',
      '#attributes' => array(
        'style' => 'margin-left: -4px; margin-top: 22px;',
      ),
    );

    // Reset the floats before rendering the Map Height element.
    $element['height'] = array(
      '#title' => t('Map Height'),
      '#type' => 'textfield',
      '#size' => 5,
      '#required' => TRUE,
      '#default_value' => $settings['height'],
      '#field_suffix' => t('px'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#prefix' => '<div style="clear: left;">',
      '#suffix' => '</div>',
    );

    $element['zoom'] = array(
      '#title' => t('Zoom Level'),
      '#description' => t('For multiple markers, the best zoom level will be auto-computed to fit them all in the map.'),
      '#type' => 'select',
      '#default_value' => $settings['zoom'],
      '#options' => variable_get('here_maps_formatter_zoom_levels'),
    );

    $element['base_map'] = array(
      '#title' => t('Base Map'),
      '#type' => 'select',
      '#default_value' => $settings['base_map'],
      '#options' => array(
        'Normal' => t('Normal'),
        'Satellite' => t('Satellite'),
        'Terrain' => t('Terrain'),
      ),
    );

    $element['connection_protocol'] = array(
      '#title' => t('Connection Protocol'),
      '#type' => 'select',
      '#default_value' => $settings['connection_protocol'],
      '#options' => array(
        'http' => t('http'),
        'https' => t('https'),
      ),
    );

    $element['map_settings'] = array(
      '#title' => t('Include Map Settings Button'),
      '#type' => 'checkbox',
      '#default_value' => $settings['map_settings'],
    );

    $element['zoom_bar'] = array(
      '#title' => t('Include Zoom Bar'),
      '#type' => 'checkbox',
      '#default_value' => $settings['zoom_bar'],
    );

    $element['scale_bar'] = array(
      '#title' => t('Include Scale Bar'),
      '#type' => 'checkbox',
      '#default_value' => $settings['scale_bar'],
    );

    $element['marker_color'] = array(
      '#title' => t('Marker Color'),
      '#description' => t("HERE Maps' default blue marker has a color value of #1188dd."),
      '#type' => 'textfield',
      '#size' => 7,
      '#required' => TRUE,
      '#default_value' => $settings['marker_color'],
      '#attributes' => array(
        'id' => 'here-maps-formatter-color-picker-target',
      ),
      '#attached' => array(
        'library' => array(
          array('system', 'farbtastic'),
        ),
        'js' => array(drupal_get_path('module', 'here_maps_formatter') . '/js/here_maps_formatter_farbtastic.js'),
      ),
      '#suffix' => '<div id="here-maps-formatter-color-picker"></div>',
    );
  }

  return $element;
}


/**
 * Implements hook_field_formatter_settings_summary().
 */
function here_maps_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();

  if ($display['type'] == 'geofield_here_maps') {
    $summary[] = t('HERE Maps Settings');

    $summary[] = t('Map Width: @width@unit', array(
      '@width' => $settings['width'],
      '@unit' => $settings['width_unit'],
      )
    );

    $summary[] = t('Map Height: @heightpx', array(
      '@height' => $settings['height'],
      )
    );

    $summary[] = t('Zoom Level: @zoom', array(
      '@zoom' => $settings['zoom'],
      )
    );

    $summary[] = t('Base Map: @base_map', array(
      '@base_map' => $settings['base_map'],
      )
    );

    $summary[] = t('Connection Protocol: @connection_protocol', array(
      '@connection_protocol' => $settings['connection_protocol'],
      )
    );

    $summary[] = t('Map Settings Button: @map_settings', array(
      '@map_settings' => _here_maps_formatter_checkbox_state_labeler($settings['map_settings']),
      )
    );

    $summary[] = t('Zoom Bar: @zoom_bar', array(
      '@zoom_bar' => _here_maps_formatter_checkbox_state_labeler($settings['zoom_bar']),
      )
    );

    $summary[] = t('Scale Bar: @scale_bar', array(
      '@scale_bar' => _here_maps_formatter_checkbox_state_labeler($settings['scale_bar']),
      )
    );

    $summary[] = t('Marker Color: @marker_color', array(
      '@marker_color' => $settings['marker_color'],
      )
    );
  }

  return implode('<br />', $summary);
}


/**
 * Implements hook_field_formatter_view().
 */
function here_maps_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings'];
  $map_width = $settings['width'];
  $map_width_unit = $settings['width_unit'];
  $map_height = $settings['height'];
  $map_zoom = $settings['zoom'];
  $base_map = $settings['base_map'];
  $connection_protocol = $settings['connection_protocol'];
  $map_settings = $settings['map_settings'];
  $zoom_bar = $settings['zoom_bar'];
  $scale_bar = $settings['scale_bar'];
  $marker_color = $settings['marker_color'];

  $element = array();

  if ($display['type'] == 'geofield_here_maps') {
    // Make sure that there are Geofield values to process.
    // This will make also the HERE Maps scripts to be loaded only
    // in selected pages to avoid affecting a page's stability and
    // its loading performance.
    if (!empty($items)) {
      // Replace the Geofield markup.
      $element[0] = array('#markup' => '<div id="here-maps" data-zoom="' . $map_zoom . '" style="width: ' . $map_width . $map_width_unit . '; height: ' . $map_height . 'px;"></div>');

      // Setup the data to be passed to JS processor.
      $data = array();
      $data['features'] = $items;
      $data['base_map'] = $base_map;
      $data['connection_protocol'] = $connection_protocol;
      $data['map_ui'] = array(
        'map_settings' => $map_settings,
        'zoom_bar' => $zoom_bar,
        'scale_bar' => $scale_bar,
      );
      $data['marker_color'] = $marker_color;

      // Load the Drupal.setings.here_maps_formatter objects.
      _here_maps_formatter_settings_loader($element, $data);

      // Load the helper scripts, attach JS scripts and CSS files.
      _here_maps_formatter_scripts_loader($element);
    }
  }

  // This is the 'edited' field, or fields for multiple-valued fields.
  return $element;
}


/**
 * Helper function for loading HERE Maps Formatter settings.
 */
function _here_maps_formatter_settings_loader(&$element, $data) {
  // Retrieve the app credential values,
  // return their default values if they're not set yet.
  $app_code = variable_get('here_maps_formatter_app_code', 'AJKnXv84fjrb0KIHawS0Tg');
  $app_id = variable_get('here_maps_formatter_app_id', 'DemoAppId01082013GAL');

  // Check if the app credentials have not been deleted on their admin form
  // or they're not set to empty values.
  $app_code = (!empty($app_code)) ? $app_code : 'AJKnXv84fjrb0KIHawS0Tg';
  $app_id = (!empty($app_id)) ? $app_id : 'DemoAppId01082013GAL';

  // Retrieve HERE Maps keys/credentials.
  $api_keys = array(
    'app_code' => $app_code,
    'app_id' => $app_id,
  );

  // Merge the formatter's data settings with that of the app's credentials.
  $settings = array_merge($data, $api_keys);

  $element['#attached']['js'][] = array(
    'data' => array('here_maps_formatter' => $settings),
    'type' => 'setting',
  );
}


/**
 * Helper function for loading HERE Maps 3.0 core and related scripts.
 */
function _here_maps_formatter_scripts_loader(&$element) {
  $here_maps_base_url = '//js.api.here.com/v3/3.0.8.0/';

  // Add the map's core functionalities.
  $element['#attached']['js'][] = array(
    'data' => $here_maps_base_url . 'mapsjs-core.js',
    'type' => 'external',
  );

  // Add the file for configuring the Platform object.
  $element['#attached']['js'][] = array(
    'data' => $here_maps_base_url . 'mapsjs-service.js',
    'type' => 'external',
  );

  // Add the file for handling map events.
  $element['#attached']['js'][] = array(
    'data' => $here_maps_base_url . 'mapsjs-mapevents.js',
    'type' => 'external',
  );

  // Add the file for binding events to the map UI elements like the zoom bar.
  $element['#attached']['js'][] = array(
    'data' => $here_maps_base_url . 'mapsjs-ui.js',
    'type' => 'external',
  );

  // Add the style file for the map.
  $element['#attached']['css'][] = array(
    'data' => $here_maps_base_url . 'mapsjs-ui.css',
    'type' => 'external',
  );

  // Load the custom HERE Maps behaviors for processing the map objects.
  $element['#attached']['js'][] = array(
    'data' => drupal_get_path('module', 'here_maps_formatter') . '/js/here_maps_formatter.js',
    'type' => 'file',
  );
}


/**
 * Helper function for converting the checkbox's state to a more readable form.
 */
function _here_maps_formatter_checkbox_state_labeler($state) {
  return ($state == 1) ? t('Enabled') : t('Disabled');
}
